disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Brandon Lo"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  copyright = "&copy; 2026 Brandon Lo. All Rights Reserved."

[params.author]
  name = "Brandon Lo"
#   email = "youremail@example.com"
  image = "profile.jpg"
#   imageQuality = 96
#   headline = "I'm only human"
#   bio = "A little bit about you"
  links = [
    { email = "brandonkwlo@gmail.com" },
    { github = "https://github.com/brandonkwlo" },
    { linkedin = "https://www.linkedin.com/in/brandon-lo-556a00169/" }
#     { link = "https://link-to-some-website.com/" },
  ]
